// src/service/dummyCategories.js
export const categories = [
  {
    id: 1,
    title: "Electronics",
    gradientFrom: "from-black",
    gradientTo: "to-green-500",
    bgColor: "bg-green",
    textColor: "text-white",
    products: [],
  },
  {
    id: 2,
    title: "Fashion",
    gradientFrom: "from-black",
    gradientTo: "to-orange-500",
    bgColor: "bg-orange",
    textColor: "text-black",
    products: [],
  },
  {
    id: 3,
    title: "Home & Living",
    gradientFrom: "from-black",
    gradientTo: "to-blue-500",
    bgColor: "bg-blue",
    textColor: "text-white",
    products: [],
  },
  {
    id: 4,
    title: "Agriculture & Livestocks",
    gradientFrom: "from-black",
    gradientTo: "to-yellow-500",
    bgColor: "bg-yellow",
    textColor: "text-black",
    products: [],
  },
  {
    id: 5,
    title: "Phone/Device",
    gradientFrom: "from-black",
    gradientTo: "to-yellow-500",
    bgColor: "bg-yellow",
    textColor: "text-black",
    products: [],
  },
  {
    id: 6,
    title: "Perfumes & Cosmetics",
    gradientFrom: "from-black",
    gradientTo: "to-purple-500",
    bgColor: "bg-purple",
    textColor: "text-white",
    products: [],
  },
];
